### ISSUE TITLE
Initialize ADYServiceParameters without /authorise WS call

### ISSUE THREAD

**Issue by tlupo** [Adyen/adyen-3ds2-ios#1]
Hello !

I use your iOS / Android SDK on my mobile application (thank you very much for your work) and I’m very interested by using 3D Secure 2.0 but I don’t how to initialize ADYServiceParameters with my current implementation. 

My current workflow : Initialize and start CheckoutViewController -> Get token (CheckoutControllerDelegate) -> Send token to my server -> Call /paymentSession WS -> Send back payment session to my mobile application (SDK handler) -> Get payload (CheckoutControllerDelegate) -> Send payload to my server -> Call /payments/result to verify the payment.

According to your README, it seems we need additionalData from /authorise WS call to initialize ADYServiceParameters. I don't use /authorise endpoint for now (it requires credit card information but I don't have this information in my current workflow). Is it possible with my current workflow to get this additionalData (with /paymentSession call for instance) ?

Thank you very much. Best regards,
Thomas

**Comment by joostvandijk** [comment]
Hey @tlupo,

Thanks for your interest in our 3D Secure 2.0 SDK! Currently, it's only available on our test environment in combination with our [classic ecommerce integration](https://docs.adyen.com/developers/classic-integration). We're working on providing an integration with our Checkout SDKs and API as well, but this is not available at the moment.

I hope this answers your question. Let me know if you need anything else.

Kind regards,

Joost

**Comment by tlupo** [comment]
Hey @joostvandijk 

Thank you for your quick answer ! I will follow the next releases and wait for Checkout SDK and API integration to use 3D Secure 2.0 on mobile side.

Thanks again ! Kind regards,
Thomas
