### ISSUE TITLE
Failed to verify bitcode in Adyen3DS2 

### ISSUE THREAD

**Issue by Venkat1128** [Adyen/adyen-3ds2-ios#10]
Hi,
I am getting below error when archiving . Any suggestions ?
exportArchive: Failed to verify bitcode in Adyen3DS2.framework/Adyen3DS2

Thanks,
Venkat

**Comment by joostvandijk** [comment]
Hi,

What version of Xcode are you using? Could you retry with the latest?

Kind regards,

Joost

**Comment by Venkat1128** [comment]
Xcode 11.0 .. i will try to update to latest 11.1

**Comment by Venkat1128** [comment]
Thanks its working after xcode update
