### ISSUE TITLE
Lexical  or Preprocessor issue   'Adyen3DS2/ADYServiceParameters.h' file not found

### ISSUE THREAD

**Issue by Venkat1128** [Adyen/adyen-3ds2-ios#11]
Hi 
I am having issue with Adyen3DS2 in latest Xcode 11.2. 
I have installed using cocoa-pods and used to work earlier. 
Now getting 'Lexical  or Preprocessor issue   'Adyen3DS2/ADYServiceParameters.h' file not found" Error 

Any suggestions?

Thanks,
Venkat

**Comment by joostvandijk** [comment]
Hi @Venkat1128,

Have you tried with the latest version of Cocoapods? Which version are you using?

Joost

**Comment by Venkat1128** [comment]
I have tried with 1.8.4 and 1.8.3 as well 
Also tried with   pod 'Adyen3DS2', '2.1.0-rc.4' and  pod 'Adyen3DS2', '2.1.0-rc.3'

**Comment by Venkat1128** [comment]
I went back to dynamic linking the framework to resolve my issue 
Thanks
