### ISSUE TITLE
iOS13 still opens performChallengeWithParameters in pageSheet

### ISSUE THREAD

**Issue by isimpson** [Adyen/adyen-3ds2-ios#12]
When calling the `performChallengeWithParameters` the challenge view is still opened in a pageSheet even though the UIViewController `modalPresentationStyle` is `.fullScreen`.

Test with the latest version 2.1.0-rc.4 which is meant to have this fix:
- Disables the default iOS 13 slide-to-dismiss behaviour.

**Comment by joostvandijk** [comment]
Hey @isimpson,

The release note refers to disabling the ability to swipe-to-dismiss the modal. The challenge view is still presented as a pagesheet. This is currently intentional.

Best,

Joost

**Comment by isimpson** [comment]
@joostvandijk thanks for the response, do you have any intention to configure this as we still want fullscreen behaviour?

**Comment by joostvandijk** [comment]
@isimpson There's currently no intention to do this, but I'll add it to the list.

**Comment by joostvandijk** [comment]
@isimpson We'll include a customization option for this in the next release.

**Comment by joostvandijk** [comment]
Hi @isimpson, the update has been released. A property has been added to the `ADYAppearanceConfiguration` to customize the modal presentation style.
