### ISSUE TITLE
New version number fails App Store Connect validation

### ISSUE THREAD

**Issue by repomies** [Adyen/adyen-3ds2-ios#15]
When trying to submit an app with the newest 2.2.0.0 version of the framework, App Store Connect gives this error:

>ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '2.2.0.0' in the Info.plist file at 'Payload/XXXX.app/Frameworks/Adyen3DS2.framework' must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

**Comment by repomies** [comment]
(As a workaround, it's possible to change the version number in Adyen3DS2.framework/Info.plist before archiving the app.)

**Comment by mohammedDehairy** [comment]
Hi @repomies ,

 Thanks for the issue.

 This was short sight from our end, we'll fix it ASAP and make a new minor release.

Kind regards

Mohamed

**Comment by mohammedDehairy** [comment]
Hi @repomies ,

 We made a new release with version number `2.2.0`, to make the version number compliant with semantic versioning.

Mohamed

**Comment by repomies** [comment]
Hi @mohammedDehairy,

Thanks for a quick fix!
