### ISSUE TITLE
EmvThreedsMessage Version Number received is not valid for the receiving component.

### ISSUE THREAD

**Issue by kanclalg** [Adyen/adyen-3ds2-ios#16]
Hi, we're getting this error when calling `performChallenge` method. It shows loading screen for a bit and then throws error. It throws same error for android and iOS on adyen-3ds2 version 2.2.0.

Error message: EmvThreedsMessage Version Number received is not valid for the receiving component.

adyen-3ds2-ios version: 2.2.0

Works fine on version 2.1.0-rc.6 and older versions I think. At least 0.9.6 also works fine.

**Comment by mohammedDehairy** [comment]
HI @kanclalg ,

 Thats probably because the issuer bank is not ready for EMVCo `2.2.0` , the 3DS 2 SDK for Android and iOS uses the highest protocol version if no version is specified.

 what you need to do is specify `2.1.0` as the protocol version when creating the transaction, like this:

```
let transaction = try service.transaction(withMessageVersion: "2.1.0")
```

**Comment by kanclalg** [comment]
Hi, @mohammedDehairy, how should I know what version is supported from the issuer bank? We are actually getting back `messageVersion` (which is 2.1.0 for that specific card) in response when calling `/pal/servlet/Payment/v51/authorise3ds2`. Maybe we should this one?

**Comment by mohammedDehairy** [comment]
Hi @kanclalg ,

Sorry for the late response, was out of office!.

You can either hard code the message version to `2.1.0` as in the code snippet above, or use the message version returned from the Authorization Response to instantiate the transaction:

```
let transaction = try service.transaction(withMessageVersion: messageVersionFromAuthorisationResponse)
```

Unfortunately as far as the SDK is concerned the merchant is in control of the message version used, either from the 3DS Server (in this case its Adyen 3DS server), or hard coded to a certain value.

Let me know if you need further help.

Mohamed

**Comment by kanclalg** [comment]
Hi @mohammedDehairy, so basically you're saying that it is configured by us. Either hardcoding it or configuring it somehow from the adyen account? What then if one issuer bank supports version 2.1.0 and another one 2.2.0? I'm a bit confused with these versions.

**Comment by mohammedDehairy** [comment]
Hi @kanclalg ,

```
so basically you're saying that it is configured by us. Either hardcoding it or configuring it somehow from the adyen account
```

Yes that's right, you hardcode it, or somehow get it from the Adyen server API response when a 3DS 2 flow is about to get initiated.

```
What then if one issuer bank supports version 2.1.0 and another one 2.2.0? 
```
if an issuer supports `2.2.0`, then by consequence they definitely support `2.1.0`, EMVCo 2.2.0 certification covers also 2.1.0 functionalities.

so specifying `2.1.0` should be safe for any issuer that supports 3DS2.

Mohamed

**Comment by kanclalg** [comment]
Thank you, @mohammedDehairy! Not sure if it's documentated anywhere, but I think it would be a great idea to do that. With a current setup configuration more people could hit this issue after their code is in production.

**Comment by mohammedDehairy** [comment]
Thanks @kanclalg , 

yes, you're right, we're aware of this lack in documentation, and we will update it ASAP.
