### ISSUE TITLE
Building for catalyst on M1 fails with SPM

### ISSUE THREAD

**Issue by sampettersson** [Adyen/adyen-3ds2-ios#17]
**Describe the bug**
While building on an M1 Mac Mini while integrated with SPM we get this error: "While building for Mac Catalyst, no library for this platform was found in '**/adyen-3ds2-ios/XCFramework/Dynamic/Adyen3DS2.xcframework'."

I assume this is because the xcframework doesn't seem to have a catalyst framework?

**Comment by mohammedDehairy** [comment]
Hi @sampettersson ,

Thanks for reaching out.

 Unfortunately `Adyen3DS2 ` is not built for a `macosx` target at the moment, but its doable,  I'll add this on our list for next release, is this blocking for your integration? how urgent is it? .

Mohamed

**Comment by sampettersson** [comment]
Hi @mohammedDehairy!

Not super urgent, but it's the last little thing making us not build on catalyst, so would be nice if it could be fixed quite soon 😄

**Comment by mohammedDehairy** [comment]
Thanks @sampettersson ,

 We'll do a release as soon as possible, probably in the coming 2-3 weeks.

**Comment by MattCheetham** [comment]
We're also looking to release our app with Mac Catalyst so we'd really appreciate this too 👍

**Comment by mohammedDehairy** [comment]
@MattCheetham , @sampettersson ,

`2.2.2` is released with support for Mac catalyst.

I am going to close this ticket for now, and you can reopen it if needed.
