### ISSUE TITLE
Message element defined as required is missing from the message.

### ISSUE THREAD

**Issue by Xioshock** [Adyen/adyen-3ds2-ios#18]
**Describe the bug**
Hi, I have upgraded from version 2.1.0-rc.1 to 2.2.1 and had to rewrite some methods for creating fingerprints and challenges. Fingerprints work fine, but when I try to perform challenge, I get the following error:

`Error Domain=com.adyen.Adyen3DS2.ADYProtocolError Code=201 "Message element defined as required is missing from the message." UserInfo={ADYProtocolErrorServerTransactionIdentifierKey=c32d65c6-546f-4e26-9d12-9e2b21e927b0, ADYProtocolErrorSDKTransactionIdentifierKey=e768f6fd-92f1-41d0-be5a-93ebf5bbdffc, ADYProtocolErrorDetailKey=challengeInfoText, ADYProtocolErrorACSTransactionIdentifierKey=b2ca24e6-265a-40da-82e8-efb0021f5809, NSLocalizedDescription=Message element defined as required is missing from the message.}`

Nothing else changed in the app. The tokens for the challenge work fine in the old version. Do we need to update our api in some way?

**Smartphone (please complete the following information):**
 - Device: iOS Simulator
 - Version 14.4

**Comment by mohammedDehairy** [comment]
Hi @Xioshock ,

Thanks for reaching out.

This error indicates that the ACS that belongs to whatever card you're using for testing sends a response that's missing a required field, namely `challengeInfoText`, in `2.1.0-rc.1` we didn't validate it, but in `2.2.1` we do, so its an issuer problem.

Besides that:

What `messageVersion` are you passing to ADYService  `transactionWithMessageVersion`  function? .

Starting `2.2.0` SDK version, you must use whatever message version that comes in the `/authorise` endpoint response, as described [here](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure/native-3ds2/ios-sdk-integration#get-the-3d-secure-2-device-fingerprint).

Mohamed

**Comment by kaserdan** [comment]
Hi, is that field required even for messageVersion `2.1.0`?
I guess the best solution is to contact the card issuer to fix this.

**Comment by mohammedDehairy** [comment]
yes, I believe its required even for messageVersion `2.1.0`.

and yes, contacting the issuer would be advisable, if you need help with this, let me know.

**Comment by Xioshock** [comment]
@mohammedDehairy thank you for the help. We'll contact the issuer

**Comment by beetsandroots** [comment]
Hello, 

Was this issue fixed for you?
