### ISSUE TITLE
Error ADYRuntimeErrorSecureChannelSetupFailed

### ISSUE THREAD

**Issue by Bazalt01** [Adyen/adyen-3ds2-ios#26]
**Describe the bug**
We found significant growth `ADYRuntimeErrorSecureChannelSetupFailed` errors from the middle of June 2021. The regular ratio of failed to succeeded operations is 0.001, but in several countries like Lithuania, Romania, Hungary it became from 0.1 to 0.24.

`ADYRuntimeErrorSecureChannelSetupFailed` is not fully clear, because the error's description just says that **secure channel setup** with the ACS **has failed**. and doesn't say where exactly the problem is. Is it a bug of ACS or your library?

Could you take a look at where the problem came from and can we/you fix it?

P.S. I already wrote to Adyen support a week ago, but no answer, and my ticket with id 2417040 was deleted I guess, because now it's unavailable. 

**To Reproduce**
1. Try to pass 3ds2 challenge

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS14.7.1
 - Browser SFSafariViewController

**Comment by nasirky** [comment]
@mohammedDehairy Hi! We are also facing a similar issue, however, the error object doesn't return anything other than
"Secure channel setup failed". There is no `acsTransID` or `threeDSServerTransID`. Can you please help

Here is the complete error we are getting
```
Error Domain=com.adyen.Adyen3DS2.ADYRuntimeError Code=1 "Secure channel setup failed." UserInfo={NSLocalizedDescription=Secure channel setup failed.}
```

**Comment by mohammedDehairy** [comment]
Hi @nasirky ,

do you have the `ADYChallengeParameters` object passed to the SDK when this error happens?

**Comment by mohammedDehairy** [comment]
would be helpful yes! if those values are for a failed transaction of course

**Comment by nasirky** [comment]
@mohammedDehairy  Here are the values for the last failed transaction

```
acsReferenceNumber: "3DS_LOA_ACS_ICIN_020200_00533"

acsTransactionIdentifier: "96ce3d46-879c-40c1-a0a4-4aa0dc3ea822"

serverTransactionIdentifier: "b94c1e0b-e5e8-485a-9995-395f2139e4c1"

acsSignedContent: "eyJ4NWMiOlsiTUlJRTJ6Q0NBOE9nQXdJQkFnSVVBTFhkZEp2c01QNEFvdTlkSmFSb1V1cTFETEl3RFFZSktvWklodmNOQVFFTEJRQXdjVEVMTUFrR0ExVUVCaE1DVlZNeERUQUxCZ05WQkFvVEJGWkpVMEV4THpBdEJnTlZCQXNUSmxacGMyRWdTVzUwWlhKdVlYUnBiMjVoYkNCVFpYSjJhV05sSUVGemMyOWphV0YwYVc5dU1TSXdJQVlEVlFRREV4bFdhWE5oSUdWRGIyMXRaWEpqWlNCSmMzTjFhVzVuSUVOQk1CNFhEVEl3TURnd05UQTFNelExTmxvWERUSXlNRFl5TWpBd01UWXdOMW93Z1lzeEZUQVRCZ05WQkFjTURGSmxaSGR2YjJRZ1EybDBlVEVUTUJFR0ExVUVDQXdLUTJGc2FXWnZjbTVwWVRFTE1Ba0dBMVVFQmhNQ1ZWTXhFREFPQmdOVkJBb01CMmt5WXlCSmJtTXhFVEFQQmdOVkJBc01DRk52Wm5SM1lYSmxNU3N3S1FZRFZRUUREQ0l6WkhNeUxuWnBjMkZ6WldOMWNtVnphV2R1TG1GamN5NXBNbU5wYm1NdVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFMblJVSmpZczlJZDZ0UVhjeE42MEZ6akNHRTduQk85RHd3VFU2MlJxZFVhdW0rVlBmeE5meFFMUnlLMlB1eUcwTHpJM1JzSFdLa0lUMzJ2UTY2ZzRnRUFHbVFVVm1HM1hXS3ptQjFRYVByZHNHWGJmRU1YZ0p0ak8wQ0J3R295eUREb3dLS2M4cVd3cG15VVQ4a2J6VVVJU1F1aGNlbTRVV0ZSYUpqRE92SWUzWnA3NVBJSHloZUlHNjFqQjZkQlBjNGpIMjVcL1wvcWVxaThSWUwyUmdneGpLRVFBMm05S2NHNzBwMlEyaFhvMW94NzZ0aVZsMTdIdCsrcFlSV3dQREFyUEFVZlVGbjFmaEMwXC9zQ1JTdXJ5M01xS0VhNVhXWVV1bkxiSGg2Z3Z5bVBGTUo4ejhnbFJER1pjSE5JcmtNcjBkN2ZPbE1xSmRkV2xZTldTNmdmUUlEQVFBQm80SUJUakNDQVVvd0RBWURWUjBUQVFIXC9CQUl3QURBZkJnTlZIU01FR0RBV2dCVGZ3eXBWTGk5Q09ucEFuWktnOTBkNTE0K0hpakJsQmdnckJnRUZCUWNCQVFSWk1GY3dMZ1lJS3dZQkJRVUhNQUtHSW1oMGRIQTZMeTlsYm5KdmJHd3VkbWx6WVdOaExtTnZiUzlsWTI5dGJTNWpaWEl3SlFZSUt3WUJCUVVITUFHR0dXaDBkSEE2THk5dlkzTndMblpwYzJFdVkyOXRMMjlqYzNBd09RWURWUjBnQkRJd01EQXVCZ1ZuZ1FNQkFUQWxNQ01HQ0NzR0FRVUZCd0lCRmhkb2RIUndPaTh2ZDNkM0xuWnBjMkV1WTI5dEwzQnJhVEFUQmdOVkhTVUVEREFLQmdnckJnRUZCUWNEQWpBekJnTlZIUjhFTERBcU1DaWdKcUFraGlKb2RIUndPaTh2Ulc1eWIyeHNMblpwYzJGallTNWpiMjB2WlVOdmJXMHVZM0pzTUIwR0ExVWREZ1FXQkJUZEFtXC9jSHFQelpxQWpQRWZxK0xUQlI5a3RzREFPQmdOVkhROEJBZjhFQkFNQ0I0QXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSkVwMHVja29WT1NsVnZ6YlhRZ1pEXC9hNkFcLzl1aHZRZTdxc05KOXAxQm1WdVVsTjI3cERETVlVSHA2Q0xsWkVkTTRVNlVPVFRaaHF5WUtzckFRdTc4am5SV0NaRUdmdk9Nc3FydGMzUTljc2dlOVJSTWs3Q2lIQ3M5N3RpdTZUOFRpM2VqQllaYk85TjRpV1ZZMjBodXNOVFBpczZINFN0b01PUFdUNHJCQVwvZUczNGRiRnFaVUV0SUxFT1NNM0psMEhsR2djT3VWXC9kUGhOWWRIUlVpWkVPOFF4TXY4RXpBaDZqZUFhc2JubWgwdEpYbGl6NUZUSVwvUzJZeDlDU1c5NFFHTXU1OTg4VnBmWnVQRWJhNGtsNDkwTWlhcTR6ZVI1SFF5aE5NV1dIWUtuSUNCQVYxMDVaSnVNUkZEQmVwMFg2S0xHU2RGS0NlWko2T3MwK1JPdDA9Il0sImFsZyI6IlBTMjU2In0.eyJhY3NFcGhlbVB1YktleSI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6ImE4Rnk4bUM5NE5Jc3k4WUd1dWNMZDAxc3ZOak5RYU1GTjhMTnpqQXNaQXciLCJ5IjoiaVlBYlZTeXhPUDl6NmRPREF4V1E2RUNqRTlWMWtfVVZHaEtfMFJTRTFSbyJ9LCJzZGtFcGhlbVB1YktleSI6eyJrdHkiOiJFQyIsImNydiI6IlAtMjU2IiwieCI6ImlnYTJOOTNYTm05VzdDUnpOMVI5SUo4SHhsaE5nWDJNdjl3eTMtRVpLam8iLCJ5IjoiVUZsdnFCWXF3TU9NeXhJYl9nQlFSSXNkeERXdXV6M2V5clRqa0llRWRIcyJ9LCJhY3NVUkwiOiJodHRwczovL2ZvcmlzZXUtdmJ2Lm15Y2FyZHBsYWNlLmNvbS9pMmNBY3NTZXJ2aWNlcy9zZXJ2aWNlcy9hY3MvM2RzL2NoYWxsZW5nZS9hcHBDcmVxP3Rva2VuPWZTdU5jZXB5SURrWDhPQkxNQ3E5JmlkPTQxNDM0NjQ1In0.LutaX4NWiyTaJhIwlOM64FsgBcBdDlCsjYtXFIAOm5XSkj4vyj35MGf6wpYsPQ6nYFfo59LN4m8lo6iL9dl_Byiq9xa30QYOmCrc_78-HOYlOMgpyT3F30wpBkXjFUddC-06jFXLwCy8SYsUDRq07SCfQRMRo4krGG1oZQECR7gmGIBW38KEKzus0O-a9hs05bQqJJUYlq6Ady-wIAJNq4ugByREFikueMQ0snUs7ePCMExQFJ3i2xCurUcKcU4tS_WlBQI-lWl3QD5AOeHALLHSnp9mRUF4dWcGyZ0Lk1xjVROYNAQWUlFSyZtHOo2fS9U8fcH-PtIgO-hIHNmE-w"

threeDSRequestorAppURL: nil
```

**Comment by mohammedDehairy** [comment]
another question? what was the brand of the card used? MasterCard or Visa or Amex ..etc?

**Comment by nasirky** [comment]
@mohammedDehairy The card is Visa

**Comment by mohammedDehairy** [comment]
Thanks @nasirky ,

 the ACS signed content sent by the issuer ACS has an invalid certificate chain, when I tried to validate the ACS Signed content against Visa certificate I got this error:

```
Error Domain=NSOSStatusErrorDomain Code=-25318 "“3ds2.visasecuresign.acs.i2cinc.com” certificate is not trusted" UserInfo={NSLocalizedDescription=“3ds2.visasecuresign.acs.i2cinc.com” certificate is not trusted, NSUnderlyingError=0x600003a87450 {Error Domain=NSOSStatusErrorDomain Code=-25318 "Certificate 0 “3ds2.visasecuresign.acs.i2cinc.com” has errors: Unable to build chain to root (possible missing intermediate);" UserInfo={NSLocalizedDescription=Certificate 0 “3ds2.visasecuresign.acs.i2cinc.com” has errors: Unable to build chain to root (possible missing intermediate);}}}
```

**Comment by nasirky** [comment]
@mohammedDehairy So what is the next step? Will Adyen contact the ACS or do we need to do it ourselves? In case we need to do it ourselves, we will need information about the ACS and also how to contact them.

**Comment by nasirky** [comment]
@mohammedDehairy One more thing I wanted to note was that the same card works using the web drop-in. So, I think the issue is with 3DS2. In the drop-in SDK, Is there a way to fallback to 3DS in case 3DS2 fails. If so, can you please point me there.

**Comment by mohammedDehairy** [comment]
@nasirky Web 3DS2 works in a different way than iOS/Android.

 its highly unlikely that its the SDK's fault, because as you can see by the error emitted by Apple framework, the certificate chain is simply broken in the ACS signed content sent by the issuer, there is nothing the SDK can do in this case.

and about the ACS contact its in here:
https://www.emvco.com/approved-registered/approved-products/?oypage=15&action=search_products&%3Bapproved_product_expiration_date=&%3Bpx_search=&%3Bemvco_product_device%5B0%5D=mobile-l1-products&sort=approved_product_pdf&sort_order=DESC

if you search for the acsReferenceNumber `3DS_LOA_ACS_ICIN_020200_00533`, this what comes up:

```
i2c Inc
Muhammad Faisal Iqbal
fiqbal@i2cinc.com
+1 650-593-5400 – Ext 4124
100 Redwood Shores Parkway Suite 100
Redwood City
94065
UNITED STATES OF AMERICA
```

**Comment by nasirky** [comment]
@mohammedDehairy Thanks you for the detailed response. In order to avoid this issue, Is there a possibility to force 3DS (instead of 3DS2) in the SDK? In other words, is there a fallback because it will be really difficult to keep track of individual cards.

I tried another card and I got another type of error. Can you please confirm if it also is an issue on the ASC? It's a different error but seems like the same topic.;

```
Error Domain=com.adyen.Adyen3DS2.ADYProtocolError Code=201 "Message element defined as required is missing from the message." UserInfo={ADYProtocolErrorServerTransactionIdentifierKey=94876c8b-382e-4300-bfea-687016e2c724, ADYProtocolErrorSDKTransactionIdentifierKey=5357e748-ec6f-4f03-b704-c09b1f01af92, ADYProtocolErrorDetailKey=oobContinueLabel, ADYProtocolErrorACSTransactionIdentifierKey=578142b5-1dfc-41b4-a02f-4671e0b964d2, NSLocalizedDescription=Message element defined as required is missing from the message.}
```

If needed, I can send you the ACS data.

**Comment by mohammedDehairy** [comment]
@nasirky 

Unfortunately not, the failure happens on the client, and the SDK doesn't control whether the transaction goes through 3DS1 or 2, sorry!.

the other error is also an ACS error, the ACS challenge response seems to be missing a required field namely `oobContinueLabel`.

I'll try to find the ACS reference number for this error.

**Comment by mohammedDehairy** [comment]
@nasirky this is the ACS that caused the `oobContinueLabel` error:

https://www.emvco.com/approved-registered/approved-products/?action=search_products&approved_product_expiration_date=&approved_product_expiration_date=2022-04-06&px_search=3DS_LOA_ACS_OPES_020200_00319&emvco_product_3dsecure%5B%5D=3ds-server-products&emvco_product_3dsecure%5B%5D=access-control-server-acs-products

```
Openway Europe S.A.
Maria Vinogradova
marketing@openwaygroup.com
+78123244891
3, rue Emile Francqui
Mont-St-Guibert
1435
BELGIUM
```

**Comment by nasirky** [comment]
@mohammedDehairy Thank you for the prompt response. I will take this information with me and discuss it with the team. 

Have a nice day :)

**Comment by mohammedDehairy** [comment]
I'll Close this issue due to lack of activity, please feel free to reopen if you still experiencing the issue.

**Comment by magdapilarczyk** [comment]
Hey @mohammedDehairy!
We have a spike of `Secure channel setup failed.` errors, happening specifically for Amex cards. We identified the ACS as `3DS_LOA_ACS_AMEX_020200_00315`.
emvco.com shows status `Expired` for this approval number: https://www.emvco.com/approved-products/?search_bar_keywords=3DS_LOA_ACS_AMEX_020200_00315 
How can we fix this? Who sets up which ACS version is used? We can see that AMEX has new active product: `3DS_LOA_DIS_AMEX_020200_00290`

Thank you!

**Comment by mohammedDehairy** [comment]
@magdapilarczyk Thanks for reaching out!

 we need more information to know for sure the cause of the issue, so can you please provide the following?:

- Some sample psp references 
- Whats your merchant account?
- When did this issue started to happen roughly if you can find out?
- What version of the 3DS2 SDK that you're using?

**Comment by himanshumattoo** [comment]
@magdapilarczyk thank you for reporting this issue. This has now been resolved. 

Please see our https://status.adyen.com/ for more update on this issue.

**Comment by magdapilarczyk** [comment]
@himanshumattoo @mohammedDehairy Awesome news! I can confirm we don't see this issue happening anymore. Thank you :)
