### ISSUE TITLE
Navigation bar colour changes when using 3DS2

### ISSUE THREAD

**Issue by MattFosterDev** [Adyen/adyen-3ds2-ios#27]
**Describe the bug**
I am using a drop in component to complete a card payment, when the 3DS2 screen appears it changes the navigation bar background colour for the entire app.

**To Reproduce**
1. Use a drop in component for card payment
2. Complete card details
3. 3DS2 screen appears, either complete or dismiss
4. See navigation bar colour has changed

**Screenshots**

![blacknavbar](https://user-images.githubusercontent.com/89350115/167433485-d2cafe3c-ad4b-4e74-a20a-6b1bdfd545cc.png)
![3ds2](https://user-images.githubusercontent.com/89350115/167433536-5414651c-6c1b-4c6a-9605-265ad713353d.png)
![whitenavbar](https://user-images.githubusercontent.com/89350115/167433559-b0829a60-77ae-4d58-b62d-eba5626d8bd6.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 13
 - OS: iOS 15.4

**Additional Details**
I have recently updated to the latest version.  I was on version 3.8.4 of Adyen and 2.2.1 of Adyen3DS2 which didn't seem to have this issue.

**Comment by descorp** [comment]
Thanks @MattFosterDev 

we will in investigate the issue!

**Comment by xfreebird** [comment]
Same issue here. I've provided details through Adyen Support.
