### ISSUE TITLE
App Store rejection due to obfuscated symbols

### ISSUE THREAD

**Issue by dbarden-mhp** [Adyen/adyen-3ds2-ios#3]
Hey all,

While integrating Adyen v2.7.0 on our application and sending it to the App Store, we got rejected based on Guideline 2.3.1

> We discovered that your app contains obfuscated code, selector mangling, or features meant to subvert the App Review process by changing this app's concept after approval to the App Store.

On further conversation with Apple, what they told us was:

> Regarding the 2.3.1 issue, this app implements the PPiOS-Renamed obfuscation library. To proceed, it would be appropriate to remove this library or to explain in detail the purpose of its inclusion.

We ended up downgrading the Adyen version to 2.5.0, which doesn't include this library. I thought it would be interesting for you to know since other applications will fall on this rule.

Would it be possible to handle obfuscation in a way that doesn't violate Apple's rules? I know that Estimote went through the [same problem](https://github.com/Estimote/iOS-SDK/issues/267)

Let me know if you have any idea on how to tackle this issue.

Thanks in advance,

**Comment by joostvandijk** [comment]
Hi @dbarden-mhp,

Thanks for letting us know! The 3D-Secure 2.0 SDK includes code obfuscation, which is required by the EMVCo and the PCI specification. We're definitely going to look into how to redo the obfuscation to make it better comply with Apple's guidelines.

Kind regards,

Joost

**Comment by dbarden-mhp** [comment]
Sent you via mail, since the app is not public yet. it was during the beta review.

**Comment by moia-killian** [comment]
Hi @joostvandijk, 

since a few days we have the same Problem with Apple. 
Are there any Updates on that?

Kind regards,
Kilian

**Comment by joostvandijk** [comment]
Hi @moia-killian,

Did you try version 0.9.6? This version should contain a fix for this issue.

Kind regards,
Joost

**Comment by moia-killian** [comment]
@joostvandijk thanks for pointing that out. We will try with the latest update.

**Comment by dbarden-mhp** [comment]
We just had a build approved using the newest version of this library.

Thanks for the support 👍

**Comment by userException** [comment]
> Hi @moia-killian,
> 
> Did you try version 0.9.6? This version should contain a fix for this issue.
> 
> Kind regards,
> Joost

hey there,

I am experiencing the same issue with one of my iOS frameworks. Could you please point me to the fix, what you did to pass apple's approval?
