### ISSUE TITLE
XCFramework to bundle static libraries

### ISSUE THREAD

**Issue by chiragramani** [Adyen/adyen-3ds2-ios#30]
I see that frameworks distribution have support for static archives and dynamic libs which is great. But I only see dylibs bundled in the distributed XCFramework.

Can we update the distribution workflow to also make a XCFramework bundling static archives?

**Comment by mohammedDehairy** [comment]
Hi @chiragramani ,

Thanks for the suggestion!, sounds like a nice idea, we'll look into it.

**Comment by chiragramani** [comment]
Thanks!

**Comment by chiragramani** [comment]
> Hi @chiragramani ,
> 
> 
> 
> Thanks for the suggestion!, sounds like a nice idea, we'll look into it.

Hey @mohammedDehairy, do you have an update on this request?

**Comment by mohammedDehairy** [comment]
@chiragramani ,

we're planning a release soon, maybe in a couple of weeks, with support for static XCFramework.

**Comment by chiragramani** [comment]
thank you, appreciate it!
