### ISSUE TITLE
PrivacyInfo file malformed

### ISSUE THREAD

**Issue by piercifani** [Adyen/adyen-3ds2-ios#38]
When uploading a binary to AppStore Connect with the 2.4.1 version of the framework, the following message is received from Apple:

<img width="894" alt="image" src="https://github.com/Adyen/adyen-3ds2-ios/assets/869981/1a4d49a7-4aaf-4f30-8ea6-681911038e93">

Please update the file in order to unblock 3rd party developers from submitting updates starting May 1 2024.

**Comment by luisfgf** [comment]
Hello, we have the same warning, NSPrivacyAccessedAPITypeReasons seems contains a new line at the end of "CA92.1" raison. Thanks

**Comment by robertdalmeida** [comment]
Thanks for raising this issue. We have created a release 2.4.2 with this issue fixed.
