### ISSUE TITLE
Unknown directory server

### ISSUE THREAD

**Issue by jnorkus** [Adyen/adyen-3ds2-ios#5]
When creating a transaction I am getting the following error:

`ERROR Error Domain=com.adyen.Adyen3DS2.ADYRuntimeError Code=0 "Unknown directory server." UserInfo={NSLocalizedDescription=Unknown directory server.}`

I am sure the directory server ID is valid because it goes through successfully on Android.

**Comment by joostvandijk** [comment]
Hi @jnorkus,

Can you show a snippet of how you initialize the service and create a transaction?

With kind regards,

Joost

**Comment by jnorkus** [comment]
Here is my implementation in Nativescript (TypeScript).

```
export class Adyen3ds2Flow {
    private parameters: ADYServiceParameters;

    constructor(directoryServerId: string, directoryServerPublicKey: string) {
        this.parameters = new ADYServiceParameters();
        this.parameters.directoryServerIdentifier = directoryServerId;
        this.parameters.directoryServerPublicKey = directoryServerPublicKey;
    }

    createTransaction() {
        return new Promise((resolve, reject) => {
ADYService.transactionWithParametersAppearanceConfigurationCompletionHandler(this.parameters, null, (transaction, warnings, error) => {
                if (warnings) {
                    console.warn(warnings);
                }

                if (error) {
                    reject(error);
                } else {
                    resolve(transaction);
                }
            });
        });
    };
}
```

The completion handler is getting called with mentioned error.

**Comment by joostvandijk** [comment]
The code looks good. Just to make sure, can you share the contents of the `directoryServerId` and `directoryServerPublicKey`?

**Comment by jnorkus** [comment]
Directory server ID: `F013371337`
Directory server public key: `eyJrdHkiOiJSU0EiLCJlIjoiQVFBQiIsIm4iOiI4VFBxZkFOWk4xSUEzcHFuMkdhUVZjZ1g4LUpWZ1Y0M2diWURtYmdTY0N5SkVSN3lPWEJqQmQyaTBEcVFBQWpVUVBXVUxZU1FsRFRKYm91bVB1aXVoeVMxUHN2NTM4UHBRRnEySkNaSERkaV85WThVZG9hbmlrU095c2NHQWtBVmJJWHA5cnVOSm1wTTBwZ0s5VGxJSWVHYlE3ZEJaR01OQVJLQXRKeTY3dVlvbVpXV0ZBbWpwM2d4SDVzNzdCR2xkaE9RUVlQTFdybDdyS0pLQlUwNm1tZlktUDNpazk5MmtPUTNEak02bHR2WmNvLThET2RCR0RKYmdWRGFmb29LUnVNd2NUTXhDdTRWYWpyNmQyZkppVXlqNUYzcVBrYng4WDl6a1c3UmlxVno2SU1qdE54NzZicmg3aU9Vd2JiWmoxYWF6VG1GQ2xEb0dyY2JxOV80Nnc9PSJ9`

**Comment by joostvandijk** [comment]
@jnorkus Are you using a version of the SDK older than `0.9.6`? Support for ID `F013371337` was added in `0.9.6`.

**Comment by jnorkus** [comment]
You are right, my CocoaPods repo was outdated, thus installing version 0.9.4. Running `pod repo update` fixes the issue. Thanks!

**Comment by badredaha** [comment]
Hi,
The same things ! 

Domain=com.adyen.Adyen3DS2.ADYRuntimeError Code=0 "Unknown directory server

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

Thanks for reaching out.

Which version of the SDK are you using?

What's the Directory server ID?

What's the Directory server public key?

**Comment by badredaha** [comment]
Hi @mohammedDehairy,


Which version of the SDK are you using?
- Adyen (3.6.0):
    - Adyen/Card (= 3.6.0)
    - Adyen/Core (= 3.6.0)
    - Adyen/DropIn (= 3.6.0)
  - Adyen/Card (3.6.0):
    - Adyen/Core
    - Adyen3DS2 (>= 2.1.0-rc.5)
  - Adyen/Core (3.6.0)
  - Adyen/DropIn (3.6.0):
    - Adyen/Card
    - Adyen/Core
  - Adyen3DS2 (2.2.0)

What's the Directory server ID? i don't know ! our team API handle this

What's the Directory server public key? i don't know ! our team API handle this

**Comment by badredaha** [comment]
the only card caused this problem is : 

5454 5454 5454 5454 | 03/2030 | 737
-- | -- | --

it's work for : 

4917 6100 0000 0000 | 03/2030 | 737
-- | -- | --

!!! what happened ?

**Comment by mohammedDehairy** [comment]
Hi @badredaha ,

The directory sever identifier in question is for Master card test environment, and unfortunately its unrecognizable by the SDK at the moment, so this error is expected and shouldn't affect production, and we'll fix this in future releases.
