### ISSUE TITLE
Customizing info labels string

### ISSUE THREAD

**Issue by gaarweg** [Adyen/adyen-3ds2-ios#6]
Hello,

I would like to customize the default info labels of the challenge presented. Is it possible ? 
I don't see any mention of that in the documentation.
![screenshot](https://user-images.githubusercontent.com/272186/60889807-2f8c7000-a25a-11e9-86a3-0cfe71678a45.png)

**Comment by joostvandijk** [comment]
Hi @gaarweg,

These labels are provided by the issuer. Right now, our simulators use these placeholder labels, which might be confusing. We'll work on changing them to something that makes a little bit more sense. In a live environment, the issuer would use this section to explain to the user why the authentication is happening.

Best,

Joost

**Comment by gaarweg** [comment]
Thanks @joostvandijk answering my question.
