### ISSUE TITLE
Challenge shopper screen stuck with loading

### ISSUE THREAD

**Issue by Venkat1128** [Adyen/adyen-3ds2-ios#8]
Hi Team,
Call to below code resulted in screen with loading icon for indefinite time.
###  **[transaction performChallengeWithParameters:parameters completionHandler:^(ADYChallengeResult *result, NSError *error) {
                                       if (result) {}**
I have sent a mail to your support team , but unfortunately yet to get response form them.
Please find the screenshot for the reference.
 
![Simulator Screen Shot - iPhone X - 2019-08-29 at 07 03 40](https://user-images.githubusercontent.com/5871460/64006418-32913780-cb0a-11e9-9f75-b01ec032b94a.png)

**Comment by joostvandijk** [comment]
Hi @Venkat1128,

I think this is the same issue as https://github.com/Adyen/adyen-3ds2-ios/issues/7. Please ensure you keep a strong reference to `ADYTransaction` during the challenge.

Best,

Joost

**Comment by Venkat1128** [comment]
screen got loaded couple of times .. but most of the times stuck with loading icon?
I can see ADYTransaction has reference before making challenge call.

**Comment by joostvandijk** [comment]
The transaction has to be kept in memory until the completion handler is called. Please ensure that is the case.

**Comment by Venkat1128** [comment]
Thanks @joostvandijk  your right  transaction is deallocated in memory ..
I have made a change its working now .. Thanks a lot
